--|-------------------------------------------------------------------------------------------------
--|	DIANA_NODE_ATTR_CLASS_NAMES
--|-------------------------------------------------------------------------------------------------
PACKAGE DIANA_NODE_ATTR_CLASS_NAMES IS

  TYPE NODE_NAME	IS (
	DN_ROOT,	DN_TXTREP,	DN_NUM_VAL,	DN_FALSE,	DN_TRUE,
	DN_NIL,	DN_LIST,	DN_SOURCELINE,	DN_ERROR,	DN_SYMBOL_REP,
	DN_HASH,	DN_VOID,	DN_VARIABLE_ID,	DN_CONSTANT_ID,	DN_NUMBER_ID,
	DN_COMPONENT_ID,	DN_DISCRIMINANT_ID,	DN_IN_ID,	DN_IN_OUT_ID,	DN_OUT_ID,
	DN_ENUMERATION_ID,	DN_CHARACTER_ID,	DN_ITERATION_ID,	DN_TYPE_ID,	DN_SUBTYPE_ID,
	DN_PRIVATE_TYPE_ID,	DN_L_PRIVATE_TYPE_ID,	DN_PROCEDURE_ID,	DN_FUNCTION_ID,
	DN_OPERATOR_ID,	DN_PACKAGE_ID,	DN_GENERIC_ID,	DN_TASK_BODY_ID,	DN_LABEL_ID,
	DN_BLOCK_LOOP_ID,	DN_ENTRY_ID,	DN_EXCEPTION_ID,	DN_ATTRIBUTE_ID,	DN_PRAGMA_ID,
	DN_ARGUMENT_ID,	DN_BLTN_OPERATOR_ID,	DN_BLOCK_MASTER,	DN_DSCRMT_DECL,
	DN_IN,	DN_OUT,	DN_IN_OUT,	DN_CONSTANT_DECL,	DN_VARIABLE_DECL,
	DN_NUMBER_DECL,	DN_EXCEPTION_DECL,	DN_DEFERRED_CONSTANT_DECL,	DN_TYPE_DECL,
	DN_SUBTYPE_DECL,	DN_TASK_DECL,	DN_GENERIC_DECL,	DN_SUBPROG_ENTRY_DECL,
	DN_PACKAGE_DECL,	DN_RENAMES_OBJ_DECL,	DN_RENAMES_EXC_DECL,
	DN_NULL_COMP_DECL,	DN_LENGTH_ENUM_REP,	DN_ADDRESS,	DN_RECORD_REP,	DN_USE,
	DN_PRAGMA,	DN_SUBPROGRAM_BODY,	DN_PACKAGE_BODY,	DN_TASK_BODY,	DN_SUBUNIT,
	DN_ENUMERATION_DEF,	DN_SUBTYPE_INDICATION,	DN_INTEGER_DEF,	DN_FLOAT_DEF,
	DN_FIXED_DEF,	DN_CONSTRAINED_ARRAY_DEF,	DN_UNCONSTRAINED_ARRAY_DEF,
	DN_ACCESS_DEF,	DN_DERIVED_DEF,	DN_RECORD_DEF,	DN_PRIVATE_DEF,	DN_L_PRIVATE_DEF,
	DN_FORMAL_DSCRT_DEF,	DN_FORMAL_INTEGER_DEF,	DN_FORMAL_FIXED_DEF,
	DN_FORMAL_FLOAT_DEF,	DN_ALTERNATIVE_S,	DN_ARGUMENT_ID_S,	DN_CHOICE_S,
	DN_COMP_REP_S,	DN_COMPLTN_UNIT_S,	DN_CONTEXT_ELEM_S,	DN_DECL_S,	DN_DSCRMT_DECL_S,
	DN_GENERAL_ASSOC_S,	DN_DISCRETE_RANGE_S,	DN_ENUM_LITERAL_S,	DN_EXP_S,
	DN_ITEM_S,	DN_INDEX_S,	DN_NAME_S,	DN_PARAM_S,	DN_PRAGMA_S,
	DN_SCALAR_S,	DN_SOURCE_NAME_S,	DN_STM_S,	DN_TEST_CLAUSE_ELEM_S,
	DN_USE_PRAGMA_S,	DN_VARIANT_S,	DN_LABELED,	DN_NULL_STM,	DN_ABORT,
	DN_RETURN,	DN_DELAY,	DN_ASSIGN,	DN_EXIT,	DN_CODE,
	DN_CASE,	DN_GOTO,	DN_RAISE,	DN_ENTRY_CALL,	DN_PROCEDURE_CALL,
	DN_ACCEPT,	DN_LOOP,	DN_BLOCK,	DN_COND_ENTRY,	DN_TIMED_ENTRY,
	DN_IF,	DN_SELECTIVE_WAIT,	DN_TERMINATE,	DN_STM_PRAGMA,	DN_NAMED,
	DN_ASSOC,	DN_USED_CHAR,	DN_USED_OBJECT_ID,	DN_USED_OP,	DN_USED_NAME_ID,
	DN_ATTRIBUTE,	DN_SELECTED,	DN_FUNCTION_CALL,	DN_INDEXED,	DN_SLICE,
	DN_ALL,	DN_SHORT_CIRCUIT,	DN_NUMERIC_LITERAL,	DN_NULL_ACCESS,	DN_RANGE_MEMBERSHIP,
	DN_TYPE_MEMBERSHIP,	DN_CONVERSION,	DN_QUALIFIED,	DN_PARENTHESIZED,	DN_AGGREGATE,
	DN_STRING_LITERAL,	DN_QUALIFIED_ALLOCATOR,	DN_SUBTYPE_ALLOCATOR,
	DN_RANGE,	DN_RANGE_ATTRIBUTE,	DN_DISCRETE_SUBTYPE,	DN_FLOAT_CONSTRAINT,
	DN_FIXED_CONSTRAINT,	DN_INDEX_CONSTRAINT,	DN_DSCRMT_CONSTRAINT,
	DN_CHOICE_EXP,	DN_CHOICE_RANGE,	DN_CHOICE_OTHERS,	DN_PROCEDURE_SPEC,	DN_FUNCTION_SPEC,
	DN_ENTRY,	DN_PACKAGE_SPEC,	DN_RENAMES_UNIT,	DN_INSTANTIATION,	DN_NAME_DEFAULT,
	DN_BOX_DEFAULT,	DN_NO_DEFAULT,	DN_BLOCK_BODY,	DN_STUB,	DN_IMPLICIT_NOT_EQ,
	DN_DERIVED_SUBPROG,	DN_COND_CLAUSE,	DN_SELECT_ALTERNATIVE,	DN_SELECT_ALT_PRAGMA,
	DN_IN_OP,	DN_NOT_IN,	DN_AND_THEN,	DN_OR_ELSE,	DN_FOR,
	DN_REVERSE,	DN_WHILE,	DN_ALTERNATIVE,	DN_ALTERNATIVE_PRAGMA,
	DN_COMP_REP,	DN_COMP_REP_PRAGMA,	DN_CONTEXT_PRAGMA,	DN_WITH,	DN_VARIANT,
	DN_VARIANT_PRAGMA,	DN_ALIGNMENT,	DN_VARIANT_PART,	DN_COMP_LIST,	DN_COMPILATION,
	DN_COMPILATION_UNIT,	DN_INDEX,	DN_TASK_SPEC,	DN_ENUMERATION,
	DN_INTEGER,	DN_FLOAT,	DN_FIXED,	DN_ARRAY,	DN_RECORD,
	DN_ACCESS,	DN_CONSTRAINED_ARRAY,	DN_CONSTRAINED_RECORD,
	DN_CONSTRAINED_ACCESS,	DN_PRIVATE,	DN_L_PRIVATE,	DN_INCOMPLETE,
	DN_UNIVERSAL_INTEGER,	DN_UNIVERSAL_FIXED,	DN_UNIVERSAL_REAL,	DN_USER_ROOT,
	DN_REAL_VAL,	DN_TRANS_WITH,	DN_LIB_INFO,	DN_DEF,	DN_ANY_ACCESS,
	DN_ANY_COMPOSITE,	DN_ANY_STRING,	DN_ANY_ACCESS_OF,	DN_ANY_INTEGER,	DN_ANY_REAL,
	DN_IMPLICIT_CONV,	DN_NULLARY_CALL,
	DN_VIRGIN
	);
	FOR NODE_NAME'SIZE USE 8;

  TYPE ATTRIBUTE_NAME	IS (
	XD_HIGH_PAGE,	XD_USER_ROOT,	XD_SOURCE_LIST,	XD_ERR_COUNT,	SPARE_1,
	XD_HEAD,	XD_TAIL,	XD_NUMBER,	XD_ERROR_LIST,	XD_SRCPOS,
	XD_TEXT,	XD_DEFLIST,	XD_LIST,	LX_SYMREP,	XD_REGION,
	SM_OBJ_TYPE,	SM_FIRST,	AS_USED_NAME_ID,	AS_GENERAL_ASSOC_S,	AS_LIST,
	AS_SOURCE_NAME,	AS_SOURCE_NAME_S,	AS_EXP,	AS_TYPE_DEF,	SM_INIT_EXP,
	SM_RENAMES_OBJ,	SM_ADDRESS,	CD_COMP_UNIT,	CD_LEVEL,	CD_OFFSET,
	CD_COMPILED,	SM_IS_SHARED,	AS_DSCRMT_DECL_S,	SM_TYPE_SPEC,	AS_SUBTYPE_INDICATION,
	XD_SOURCE_NAME,	SM_DERIVED,	SM_IS_ANONYMOUS,	SM_BASE_TYPE,	SM_RANGE,
	CD_IMPL_SIZE,	SM_ACCURACY,	SM_SIZE,	SM_IS_LIMITED,	SM_IS_PACKED,
	SM_DEPENDS_ON_DSCRMT,	CD_ALIGNMENT,	AS_CONSTRAINT,	AS_NAME,
	XD_DERIVED_SUBPROG_LIST,	AS_EXP1,	AS_EXP2,	AS_ENUM_LITERAL_S,
	CD_LAST,	SM_LITERAL_S,	SM_POS,	SM_REP,	AS_RANGE,
	CD_IMPL_SMALL,	AS_DISCRETE_RANGE_S,	AS_INDEX_S,	SM_INDEX_S,
	SM_COMP_TYPE,	SM_INDEX_SUBTYPE_S,	CD_DIMENSIONS,	AS_COMP_LIST,	SM_DISCRIMINANT_S,
	SM_COMP_LIST,	SM_REPRESENTATION,	SM_NORMALIZED_DSCRMT_S,	SM_COMP_REP,
	AS_VARIANT_S,	AS_CHOICE_S,	CD_LABEL,	AS_DECL_S,	AS_VARIANT_PART,
	AS_PRAGMA_S,	AS_PRAGMA,	AS_DISCRETE_RANGE,	SM_STORAGE_SIZE,	SM_IS_CONTROLLED,
	SM_DESIG_TYPE,	SM_MASTER,	CD_CONSTRAINED,	XD_FULL_TYPE_SPEC,	AS_HEADER,
	AS_UNIT_KIND,	SM_EXP_TYPE,	SM_VALUE,	SM_DEFN,	AS_EXP_S,
	AS_DESIGNATOR,	SM_NORMALIZED_COMP_S,	AS_SHORT_CIRCUIT_OP,
	AS_MEMBERSHIP_OP,	SM_DISCRETE_RANGE,	LX_NUMREP,	AS_QUALIFIED,	AS_STM,
	AS_TEST_CLAUSE_ELEM_S,	AS_STM_S,	SM_STM,	AS_ALTERNATIVE_S,
	AS_ITERATION,	CD_AFTER_LOOP,	AS_BLOCK_BODY,	AS_ITEM_S,	CD_RETURN_LABEL,
	CD_RESULT_OFFSET,	SM_SPEC,	XD_STUB,	XD_BODY,	SM_UNIT_DESC,
	SM_IS_INLINE,	SM_INTERFACE,	CD_PARAM_SIZE,	SM_DERIVABLE,	SM_EQUAL,
	CD_RESULT_SIZE,	XD_NOT_EQUAL,	AS_PARAM_S,	LX_DEFAULT,	CD_ADDR_OFFSET,
	CD_VAL_OFFSET,	SM_NORMALIZED_PARAM_S,	LX_PREFIX,	AS_USED_NAME,
	AS_DECL_S1,	AS_DECL_S2,	XD_BODY_IS_REQUIRED,	AS_NAME_S,
	AS_TYPE_MARK_NAME,	SM_DECL_S,	SM_BODY,	AS_STM_S1,	AS_STM_S2,
	AS_COMPLTN_UNIT_S,	AS_CONTEXT_ELEM_S,	AS_ALL_DECL,	XD_TIMESTAMP,	XD_WITH_LIST,
	XD_NBR_PAGES,	XD_PARENT,	XD_LIB_NAME,	AS_USE_PRAGMA_S,	AS_SUBUNIT_BODY,
	AS_BODY,	SM_RENAMES_EXC,	SM_GENERIC_PARAM_S,	AS_ALIGNMENT_CLAUSE,
	AS_COMP_REP_S,	XD_POS,	SM_OPERATOR,	SM_ARGUMENT_ID_S,	LX_SRCPOS,
	XD_SOURCENAME,	XD_GRAMMAR,	XD_STATELIST,	XD_STRUCTURE,	SPARE_3,
	XD_NUMER,	XD_DENOM,	TW_FILENAME,	TW_COMP_UNIT,	XD_SHORT,
	XD_PRIMARY,	XD_SECONDARY,	XD_ITEM,	XD_HEADER,	XD_REGION_DEF,
	XD_IS_IN_SPEC,	XD_LEX_LEVEL,	XD_IS_USED
	);

  SUBTYPE CLASS_STANDARD_IDL	IS NODE_NAME RANGE DN_ROOT	.. DN_VOID;
  SUBTYPE CLASS_BOOLEAN	IS NODE_NAME RANGE DN_FALSE	.. DN_TRUE;
  SUBTYPE CLASS_ALL_SOURCE	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_INDEX;
  SUBTYPE CLASS_DEF_NAME	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_BLTN_OPERATOR_ID;
  SUBTYPE CLASS_SOURCE_NAME	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_EXCEPTION_ID;
  SUBTYPE CLASS_OBJECT_NAME	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_ITERATION_ID;
  SUBTYPE CLASS_INIT_OBJECT_NAME	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_OUT_ID;
  SUBTYPE CLASS_VC_NAME	IS NODE_NAME RANGE DN_VARIABLE_ID	.. DN_CONSTANT_ID;
  SUBTYPE CLASS_COMP_NAME	IS NODE_NAME RANGE DN_COMPONENT_ID	.. DN_DISCRIMINANT_ID;
  SUBTYPE CLASS_PARAM_NAME	IS NODE_NAME RANGE DN_IN_ID	.. DN_OUT_ID;
  SUBTYPE CLASS_PARAM_IO_O	IS NODE_NAME RANGE DN_IN_OUT_ID	.. DN_OUT_ID;
  SUBTYPE CLASS_ENUM_LITERAL	IS NODE_NAME RANGE DN_ENUMERATION_ID	.. DN_CHARACTER_ID;
  SUBTYPE CLASS_TYPE_NAME	IS NODE_NAME RANGE DN_TYPE_ID	.. DN_L_PRIVATE_TYPE_ID;
  SUBTYPE CLASS_UNIT_NAME	IS NODE_NAME RANGE DN_PROCEDURE_ID	.. DN_TASK_BODY_ID;
  SUBTYPE CLASS_NON_TASK_NAME	IS NODE_NAME RANGE DN_PROCEDURE_ID	.. DN_GENERIC_ID;
  SUBTYPE CLASS_SUBPROG_PACK_NAME	IS NODE_NAME RANGE DN_PROCEDURE_ID	.. DN_PACKAGE_ID;
  SUBTYPE CLASS_SUBPROG_NAME	IS NODE_NAME RANGE DN_PROCEDURE_ID	.. DN_OPERATOR_ID;
  SUBTYPE CLASS_LABEL_NAME	IS NODE_NAME RANGE DN_LABEL_ID	.. DN_BLOCK_LOOP_ID;
  SUBTYPE CLASS_PREDEF_NAME	IS NODE_NAME RANGE DN_ATTRIBUTE_ID	.. DN_BLTN_OPERATOR_ID;
  SUBTYPE CLASS_ALL_DECL	IS NODE_NAME RANGE DN_BLOCK_MASTER	.. DN_SUBUNIT;
  SUBTYPE CLASS_ITEM	IS NODE_NAME RANGE DN_DSCRMT_DECL	.. DN_TASK_BODY;
  SUBTYPE CLASS_DSCRMT_PARAM_DECL	IS NODE_NAME RANGE DN_DSCRMT_DECL	.. DN_IN_OUT;
  SUBTYPE CLASS_PARAM	IS NODE_NAME RANGE DN_IN	.. DN_IN_OUT;
  SUBTYPE CLASS_DECL	IS NODE_NAME RANGE DN_CONSTANT_DECL	.. DN_PRAGMA;
  SUBTYPE CLASS_ID_S_DECL	IS NODE_NAME RANGE DN_CONSTANT_DECL	.. DN_DEFERRED_CONSTANT_DECL;
  SUBTYPE CLASS_EXP_DECL	IS NODE_NAME RANGE DN_CONSTANT_DECL	.. DN_NUMBER_DECL;
  SUBTYPE CLASS_OBJECT_DECL	IS NODE_NAME RANGE DN_CONSTANT_DECL	.. DN_VARIABLE_DECL;
  SUBTYPE CLASS_ID_DECL	IS NODE_NAME RANGE DN_TYPE_DECL	.. DN_RENAMES_EXC_DECL;
  SUBTYPE CLASS_UNIT_DECL	IS NODE_NAME RANGE DN_GENERIC_DECL	.. DN_PACKAGE_DECL;
  SUBTYPE CLASS_NON_GENERIC_DECL	IS NODE_NAME RANGE DN_SUBPROG_ENTRY_DECL	.. DN_PACKAGE_DECL;
  SUBTYPE CLASS_SIMPLE_RENAME_DECL	IS NODE_NAME RANGE DN_RENAMES_OBJ_DECL	.. DN_RENAMES_EXC_DECL;
  SUBTYPE CLASS_REP	IS NODE_NAME RANGE DN_LENGTH_ENUM_REP	.. DN_RECORD_REP;
  SUBTYPE CLASS_NAMED_REP	IS NODE_NAME RANGE DN_LENGTH_ENUM_REP	.. DN_ADDRESS;
  SUBTYPE CLASS_USE_PRAGMA	IS NODE_NAME RANGE DN_USE	.. DN_PRAGMA;
  SUBTYPE CLASS_SUBUNIT_BODY	IS NODE_NAME RANGE DN_SUBPROGRAM_BODY	.. DN_TASK_BODY;
  SUBTYPE CLASS_TYPE_DEF	IS NODE_NAME RANGE DN_ENUMERATION_DEF	.. DN_FORMAL_FLOAT_DEF;
  SUBTYPE CLASS_CONSTRAINED_DEF	IS NODE_NAME RANGE DN_SUBTYPE_INDICATION	.. DN_FIXED_DEF;
  SUBTYPE CLASS_ARR_ACC_DER_DEF	IS NODE_NAME RANGE DN_CONSTRAINED_ARRAY_DEF	.. DN_DERIVED_DEF;
  SUBTYPE CLASS_SEQUENCES	IS NODE_NAME RANGE DN_ALTERNATIVE_S	.. DN_VARIANT_S;
  SUBTYPE CLASS_STM_ELEM	IS NODE_NAME RANGE DN_LABELED	.. DN_STM_PRAGMA;
  SUBTYPE CLASS_STM	IS NODE_NAME RANGE DN_LABELED	.. DN_TERMINATE;
  SUBTYPE CLASS_STM_WITH_EXP	IS NODE_NAME RANGE DN_RETURN	.. DN_CASE;
  SUBTYPE CLASS_STM_WITH_EXP_NAME	IS NODE_NAME RANGE DN_ASSIGN	.. DN_CODE;
  SUBTYPE CLASS_STM_WITH_NAME	IS NODE_NAME RANGE DN_GOTO	.. DN_PROCEDURE_CALL;
  SUBTYPE CLASS_CALL_STM	IS NODE_NAME RANGE DN_ENTRY_CALL	.. DN_PROCEDURE_CALL;
  SUBTYPE CLASS_BLOCK_LOOP	IS NODE_NAME RANGE DN_LOOP	.. DN_BLOCK;
  SUBTYPE CLASS_ENTRY_STM	IS NODE_NAME RANGE DN_COND_ENTRY	.. DN_TIMED_ENTRY;
  SUBTYPE CLASS_CLAUSES_STM	IS NODE_NAME RANGE DN_IF	.. DN_SELECTIVE_WAIT;
  SUBTYPE CLASS_GENERAL_ASSOC	IS NODE_NAME RANGE DN_NAMED	.. DN_SUBTYPE_ALLOCATOR;
  SUBTYPE CLASS_NAMED_ASSOC	IS NODE_NAME RANGE DN_NAMED	.. DN_ASSOC;
  SUBTYPE CLASS_EXP	IS NODE_NAME RANGE DN_USED_CHAR	.. DN_SUBTYPE_ALLOCATOR;
  SUBTYPE CLASS_NAME	IS NODE_NAME RANGE DN_USED_CHAR	.. DN_ALL;
  SUBTYPE CLASS_DESIGNATOR	IS NODE_NAME RANGE DN_USED_CHAR	.. DN_USED_NAME_ID;
  SUBTYPE CLASS_USED_OBJECT	IS NODE_NAME RANGE DN_USED_CHAR	.. DN_USED_OBJECT_ID;
  SUBTYPE CLASS_USED_NAME	IS NODE_NAME RANGE DN_USED_OP	.. DN_USED_NAME_ID;
  SUBTYPE CLASS_NAME_EXP	IS NODE_NAME RANGE DN_ATTRIBUTE	.. DN_ALL;
  SUBTYPE CLASS_NAME_VAL	IS NODE_NAME RANGE DN_ATTRIBUTE	.. DN_FUNCTION_CALL;
  SUBTYPE CLASS_EXP_EXP	IS NODE_NAME RANGE DN_SHORT_CIRCUIT	.. DN_SUBTYPE_ALLOCATOR;
  SUBTYPE CLASS_EXP_VAL	IS NODE_NAME RANGE DN_SHORT_CIRCUIT	.. DN_PARENTHESIZED;
  SUBTYPE CLASS_EXP_VAL_EXP	IS NODE_NAME RANGE DN_RANGE_MEMBERSHIP	.. DN_PARENTHESIZED;
  SUBTYPE CLASS_MEMBERSHIP	IS NODE_NAME RANGE DN_RANGE_MEMBERSHIP	.. DN_TYPE_MEMBERSHIP;
  SUBTYPE CLASS_QUAL_CONV	IS NODE_NAME RANGE DN_CONVERSION	.. DN_QUALIFIED;
  SUBTYPE CLASS_AGG_EXP	IS NODE_NAME RANGE DN_AGGREGATE	.. DN_STRING_LITERAL;
  SUBTYPE CLASS_CONSTRAINT	IS NODE_NAME RANGE DN_RANGE	.. DN_DSCRMT_CONSTRAINT;
  SUBTYPE CLASS_DISCRETE_RANGE	IS NODE_NAME RANGE DN_RANGE	.. DN_DISCRETE_SUBTYPE;
  SUBTYPE CLASS_RANGE	IS NODE_NAME RANGE DN_RANGE	.. DN_RANGE_ATTRIBUTE;
  SUBTYPE CLASS_REAL_CONSTRAINT	IS NODE_NAME RANGE DN_FLOAT_CONSTRAINT	.. DN_FIXED_CONSTRAINT;
  SUBTYPE CLASS_CHOICE	IS NODE_NAME RANGE DN_CHOICE_EXP	.. DN_CHOICE_OTHERS;
  SUBTYPE CLASS_HEADER	IS NODE_NAME RANGE DN_PROCEDURE_SPEC	.. DN_PACKAGE_SPEC;
  SUBTYPE CLASS_SUBP_ENTRY_HEADER	IS NODE_NAME RANGE DN_PROCEDURE_SPEC	.. DN_ENTRY;
  SUBTYPE CLASS_UNIT_DESC	IS NODE_NAME RANGE DN_RENAMES_UNIT	.. DN_DERIVED_SUBPROG;
  SUBTYPE CLASS_UNIT_KIND	IS NODE_NAME RANGE DN_RENAMES_UNIT	.. DN_NO_DEFAULT;
  SUBTYPE CLASS_RENAME_INSTANT	IS NODE_NAME RANGE DN_RENAMES_UNIT	.. DN_INSTANTIATION;
  SUBTYPE CLASS_GENERIC_PARAM	IS NODE_NAME RANGE DN_NAME_DEFAULT	.. DN_NO_DEFAULT;
  SUBTYPE CLASS_BODY	IS NODE_NAME RANGE DN_BLOCK_BODY	.. DN_STUB;
  SUBTYPE CLASS_TEST_CLAUSE_ELEM	IS NODE_NAME RANGE DN_COND_CLAUSE	.. DN_SELECT_ALT_PRAGMA;
  SUBTYPE CLASS_TEST_CLAUSE	IS NODE_NAME RANGE DN_COND_CLAUSE	.. DN_SELECT_ALTERNATIVE;
  SUBTYPE CLASS_MEMBERSHIP_OP	IS NODE_NAME RANGE DN_IN_OP	.. DN_NOT_IN;
  SUBTYPE CLASS_SHORT_CIRCUIT_OP	IS NODE_NAME RANGE DN_AND_THEN	.. DN_OR_ELSE;
  SUBTYPE CLASS_ITERATION	IS NODE_NAME RANGE DN_FOR	.. DN_WHILE;
  SUBTYPE CLASS_FOR_REV	IS NODE_NAME RANGE DN_FOR	.. DN_REVERSE;
  SUBTYPE CLASS_ALTERNATIVE_ELEM	IS NODE_NAME RANGE DN_ALTERNATIVE	.. DN_ALTERNATIVE_PRAGMA;
  SUBTYPE CLASS_COMP_REP_ELEM	IS NODE_NAME RANGE DN_COMP_REP	.. DN_COMP_REP_PRAGMA;
  SUBTYPE CLASS_CONTEXT_ELEM	IS NODE_NAME RANGE DN_CONTEXT_PRAGMA	.. DN_WITH;
  SUBTYPE CLASS_VARIANT_ELEM	IS NODE_NAME RANGE DN_VARIANT	.. DN_VARIANT_PRAGMA;
  SUBTYPE CLASS_ALIGNMENT_CLAUSE	IS NODE_NAME RANGE DN_ALIGNMENT	.. DN_ALIGNMENT;
  SUBTYPE CLASS_VARIANT_PART	IS NODE_NAME RANGE DN_VARIANT_PART	.. DN_VARIANT_PART;
  SUBTYPE CLASS_TYPE_SPEC	IS NODE_NAME RANGE DN_TASK_SPEC	.. DN_UNIVERSAL_REAL;
  SUBTYPE CLASS_DERIVABLE_SPEC	IS NODE_NAME RANGE DN_TASK_SPEC	.. DN_L_PRIVATE;
  SUBTYPE CLASS_FULL_TYPE_SPEC	IS NODE_NAME RANGE DN_TASK_SPEC	.. DN_CONSTRAINED_ACCESS;
  SUBTYPE CLASS_NON_TASK	IS NODE_NAME RANGE DN_ENUMERATION	.. DN_CONSTRAINED_ACCESS;
  SUBTYPE CLASS_SCALAR	IS NODE_NAME RANGE DN_ENUMERATION	.. DN_FIXED;
  SUBTYPE CLASS_REAL	IS NODE_NAME RANGE DN_FLOAT	.. DN_FIXED;
  SUBTYPE CLASS_UNCONSTRAINED	IS NODE_NAME RANGE DN_ARRAY	.. DN_ACCESS;
  SUBTYPE CLASS_UNCONSTRAINED_COMPOSITE	IS NODE_NAME RANGE DN_ARRAY	.. DN_RECORD;
  SUBTYPE CLASS_CONSTRAINED	IS NODE_NAME RANGE DN_CONSTRAINED_ARRAY	.. DN_CONSTRAINED_ACCESS;
  SUBTYPE CLASS_PRIVATE_SPEC	IS NODE_NAME RANGE DN_PRIVATE	.. DN_L_PRIVATE;
  SUBTYPE CLASS_NON_DIANA	IS NODE_NAME RANGE DN_USER_ROOT	.. DN_NULLARY_CALL;
  SUBTYPE CLASS_UNSPECIFIED_TYPE	IS NODE_NAME RANGE DN_ANY_ACCESS	.. DN_ANY_REAL;


--|-------------------------------------------------------------------------------------------------
END DIANA_NODE_ATTR_CLASS_NAMES;
