--|-------------------------------------------------------------------------------------------------
--|	LALRIDL_NODE_ATTR_CLASS_NAMES
--|-------------------------------------------------------------------------------------------------
PACKAGE LALRIDL_NODE_ATTR_CLASS_NAMES IS

  TYPE NODE_NAME	IS (
	DN_ROOT,	DN_TXTREP,	DN_NUM_VAL,	DN_FALSE,	DN_TRUE,
	DN_NIL,	DN_LIST,	DN_SOURCELINE,	DN_ERROR,	DN_SYMBOL_REP,
	DN_HASH,	DN_USER_ROOT,	DN_RULE_S,	DN_RULE,	DN_ALT,
	DN_TERMINAL,	DN_NONTERMINAL,	DN_RULEINFO,	DN_STATE_S,	DN_STATE,
	DN_VOID,	DN_ITEM,	DN_TERMINAL_S,	DN_SEM_S,	DN_SEM_NODE,
	DN_SEM_OP,
	DN_VIRGIN
	);
	FOR NODE_NAME'SIZE USE 8;

  TYPE ATTRIBUTE_NAME	IS (
	XD_HIGH_PAGE,	XD_USER_ROOT,	XD_SOURCE_LIST,	XD_ERR_COUNT,	SPARE_1,
	XD_HEAD,	XD_TAIL,	XD_NUMBER,	XD_ERROR_LIST,	XD_SRCPOS,
	XD_TEXT,	XD_DEFLIST,	XD_LIST,	XD_SOURCENAME,	XD_GRAMMAR,
	XD_STATELIST,	XD_STRUCTURE,	XD_TIMESTAMP,	SPARE_3,	XD_NAME,
	XD_IS_NULLABLE,	XD_RULEINFO,	LX_SRCPOS,	XD_ALT_NBR,	XD_RULE,
	XD_STATE_S,	XD_SEMANTICS,	XD_SYMREP,	XD_TER_NBR,	XD_IS_REACHABLE,
	XD_GENS_TER_STR,	XD_TIMECHECKED,	XD_TIMECHANGED,	XD_RULE_NBR,	XD_INIT_NONTER_S,
	XD_STATE_NBR,	XD_ALTERNATIVE,	XD_ALT_TAIL,	XD_SYL_NBR,	XD_GOTO,
	XD_FOLLOW,	XD_SEM_INDEX,	XD_SEM_OP,	XD_KIND
	);

  SUBTYPE CLASS_NON_DIANA	IS NODE_NAME RANGE DN_ROOT	.. DN_SEM_OP;
  SUBTYPE CLASS_BOOLEAN	IS NODE_NAME RANGE DN_FALSE	.. DN_TRUE;
  SUBTYPE CLASS_RULE_S	IS NODE_NAME RANGE DN_RULE_S	.. DN_RULE_S;
  SUBTYPE CLASS_SYLLABLE	IS NODE_NAME RANGE DN_TERMINAL	.. DN_NONTERMINAL;
  SUBTYPE CLASS_STATE_VOID	IS NODE_NAME RANGE DN_STATE	.. DN_VOID;
  SUBTYPE CLASS_SEMANTICS	IS NODE_NAME RANGE DN_SEM_NODE	.. DN_SEM_OP;


--|-------------------------------------------------------------------------------------------------
END LALRIDL_NODE_ATTR_CLASS_NAMES;
