WITH TEXT_IO, CALENDAR;
USE  TEXT_IO, CALENDAR;
WITH IDL, CODE_GEN;
--|-------------------------------------------------------------------------------------------------
--|		ADA_COMP
--|-------------------------------------------------------------------------------------------------
PROCEDURE ADA_COMP IS
  COMMAND			: STRING( 1..512 );						--| SUPPOSEE GENEREE PAR JGRASP VIA UN SCRIPT APPELANT DONNANT LE STDIN
  CMD_LENGTH		: NATURAL;
  NOM_TEXTE		: STRING( 1..256 );
  NOM_TEXTE_LENGTH		: NATURAL;
  OPTION			: CHARACTER;
  TIME_1, TIME_2		: CALENDAR.TIME;
BEGIN
--	CHEMIN_REPERTOIRE_PROJET   CHEMIN_RELATIF_SOURCE  LETTRES_OPTIONS
  GET_LINE( COMMAND, CMD_LENGTH );

  DECLARE
    NC1	: NATURAL	:= 1;			--| INDICE DEBUT DE CHAINE
    NC2	: NATURAL	:= 0;			--| INDICE POST CHAINE
  BEGIN

ISOLE_PROJECT_DIR_PATH:
    BEGIN
      LOOP EXIT WHEN COMMAND( NC1 ) /= ' '; NC1 := NC1 + 1; END LOOP;
      NC2 := NC1 + 1;
      LOOP EXIT WHEN COMMAND( NC2 ) = ' ';  NC2 := NC2 + 1; END LOOP;

      IDL.PROJECT_PATH_LENGTH := NC2 - NC1;
      IDL.PROJECT_PATH( 1..IDL.PROJECT_PATH_LENGTH ) := COMMAND( NC1 .. NC2-1 );
    END ISOLE_PROJECT_DIR_PATH;

    IDL.LIB_PATH_LENGTH := IDL.PROJECT_PATH_LENGTH + IDL.DEFAULT_LIB_PATH'LENGTH;
    IDL.LIB_PATH( 1..IDL.LIB_PATH_LENGTH ) := IDL.PROJECT_PATH( 1 .. IDL.PROJECT_PATH_LENGTH ) & IDL.DEFAULT_LIB_PATH;

ISOLE_RELATIVE_SOURCE_PATH:
    BEGIN
      NC1 := NC2;
      LOOP EXIT WHEN COMMAND( NC1 ) /= ' '; NC1 := NC1 + 1; END LOOP;
      NC2 := NC1 + 1;
      LOOP EXIT WHEN COMMAND( NC2 ) = ' ';  NC2 := NC2 + 1; END LOOP;

      NOM_TEXTE_LENGTH := (NC2 - NC1);
      NOM_TEXTE( 1..NOM_TEXTE_LENGTH ) := COMMAND( NC1 .. NC2-1 );

    END ISOLE_RELATIVE_SOURCE_PATH;

ISOLE_OPTION:
    BEGIN
      NC1 := NC2;
      LOOP EXIT WHEN COMMAND( NC1 ) /= ' '; NC1 := NC1 + 1; END LOOP;
      OPTION := COMMAND( NC1 );
    END ISOLE_OPTION;
  END;

  PUT_LINE ( "ADA83 " & NOM_TEXTE( 1..NOM_TEXTE_LENGTH ) );

  IF OPTION = 'U' OR OPTION = 'P' OR OPTION = 'A' THEN
    IDL.PRETTY_DIANA( OPTION );
    GOTO FIN;
  END IF;

  TIME_1 := CLOCK;
  IDL.PAR_PHASE ( NOM_TEXTE( 1..NOM_TEXTE_LENGTH ), IDL.LIB_PATH );
  PUT( 'S' ); IF OPTION = 'S' THEN GOTO FIN; END IF;
  IDL.LIB_PHASE;
  PUT( 'L' ); IF OPTION = 'L' THEN GOTO FIN; END IF;
  IDL.SEM_PHASE;
  PUT( 'M' ); IF OPTION = 'M' THEN GOTO FIN; END IF;
  IDL.ERR_PHASE;
  PUT( 'E' ); IF OPTION = 'E' THEN GOTO FIN; END IF;
  IDL.WRITE_LIB;
  PUT( 'W' ); IF OPTION = 'W' THEN GOTO FIN; END IF;
  CODE_GEN;
  PUT( 'C' ); 
<<FIN>>
  TIME_2 := CLOCK;
  PUT( "..Ok" & INTEGER'IMAGE( INTEGER( 1000 * (TIME_2 - TIME_1) ) ) & " msec" );

--|-------------------------------------------------------------------------------------------------
END ADA_COMP;
