#!/bin/bash

./a83.sh ./ _STANDRD.ADA W
./a83.sh ./ SYSTEM.ADA W
./a83.sh ./ CALENDAR.ADA W
./a83.sh ./ IO_EXCEPTIONS.ADA W
./a83.sh ./ DIRECT_IO.ADA W
./a83.sh ./ SEQUENTIAL_IO.ADA W
./a83.sh ./ TEXT_IO.ADA W
./a83.sh ./ UNCHECKED_CONVERSION.ADA W
./a83.sh ./ UNCHECKED_DEALLOCATION.ADA W