WITH SEQUENTIAL_IO;
PROCEDURE TEST IS

  TYPE THE_RECORD	IS RECORD
		  CHAMP	: INTEGER;
		END RECORD;

  THE_VAR	: THE_RECORD;

  PACKAGE THE_RECORD_IO	IS NEW SEQUENTIAL_IO( THE_RECORD );

  REC_FILE	: THE_RECORD_IO.FILE_TYPE;

BEGIN
  THE_RECORD_IO.READ( REC_FILE, THE_VAR );
END;
