--|-------------------------------------------------------------------------------------------------
--|	IDL.IDL	Vincent MORIN 25-Jan-2007
--|-------------------------------------------------------------------------------------------------

--|#################################################################################################
--|	Eléments standard à toujours mettre (utilisés par le système de gestion d'arbre)
--|#################################################################################################
//  root	=>				--| Pointeur à la racine système
//		xd_high_page	: num_val,		--| Dernier bloc du fichier arbre
//		xd_user_root	: user_root,		--| Pointeur à la racine de l'arbre
//		xd_source_list	: Seq Of sourceline,	--| Pointeur à la liste des lignes sources
//		xd_err_count	: num_val,		--| Nombre d'erreurs
//		spare_1 	: void;		--| Libre
//  txtrep	=>;				--| Representation du texte
//  num_val	=>;				--| Representation d'entier 16 bits
//  BOOLEAN	::=	false | true;			--| Classe booléen
//  false	=>;				--| Valeur fausse
//  true	=>;				--| Valeur vraie
//  nil	=>;				--| Pointeur vide
//  list	=>				--| Elément lien de liste
//		xd_head 	: void,		--| Tête (pointeur à l'élément)
//		xd_tail 	: void;		--| Suite (pointeur à un élément de liste en général, ou vide)
//  sourceline	=>				--| Ligne de source
//		xd_number	: num_val,		--| Numéro de ligne
//		xd_error_list	: Seq Of error;		--| Pointeur à la liste d'erreurs
//  error	=>
//		xd_srcpos	: Source_Position,		--| Position de l'erreur (ligne colonne)
//		xd_text 	: txtrep;		--| Texte de l'erreur
//  symbol_rep	=>				--| Symbole (identificateur unique répertorié)
//		xd_text 	: txtrep,		--| Pointeur de texte symbole
//		xd_deflist	: Seq Of DEF_NAME;		--| Liste des apparitions du symbole
//  hash	=>				--| Seau de hachage
//		xd_list 	: Seq Of symbol_rep;	--| Liste de symboles du seau
//  void	=>;

//  NON_DIANA	::=	root | txtrep | num_val | BOOLEAN | nil | list	--| Classe des noeuds hors syntaxe propre
//		| sourceline | error | symbol_rep | hash | void;

--|-------------------------------------------------------------------------------------------------


--|#################################################################################################
--|	Eléments utilisateur
--|#################################################################################################

//  user_root	=>				--| Pointeur à la racine système
//		xd_sourcename	: txtrep,		--| Nom du fichier source
//		xd_rule_s	: Seq Of class_node;	--| Liste des noeuds ou classes
--|-------------------------------------------------------------------------------------------------
//  NAMED_ELEMENT	::=	class_node | ATTR_MEMBER;
//  NAMED_ELEMENT	=>	xd_symrep	: symbol_rep,		--| Symbole du nom
//		lx_srcpos	: Source_Position;		--| Position dans le source
--|-------------------------------------------------------------------------------------------------
//  class_node	=>	xd_right_side	: Seq Of ATTR_MEMBER,	--| Liste des attributs typés et/ou des membres
//		xd_is_class	: BOOLEAN,		--| Si définit une classe
//		xd_parent	: class_node,		--| Classe parente
//		xd_node_id	: num_val;		--| Numéro de noeud
--|-------------------------------------------------------------------------------------------------
//  ATTR_MEMBER	::=	attr | member;
--|-------------------------------------------------------------------------------------------------
//  attr	=>	xd_attr_id	: num_val,		--| Numéro d'attribut
//		xd_attr_type	: symbol_rep;		--| Symbole du type de l'attribut
--|-------------------------------------------------------------------------------------------------
//  member	=>	xd_class_node	: class_node;		--| Renvoi au class_node définition
--|-------------------------------------------------------------------------------------------------
//  NON_DIANA	::=	user_root | NAMED_ELEMENT;

--|#################################################################################################

// end					--| Fin de spécification
