//--LALRIDL.IDL 24-Mar-88

--Standard initial IDL items

//  root	=>				--| Pointeur à la racine système
//		xd_high_page	: num_val,		--| Dernier bloc du fichier arbre
//		xd_user_root	: user_root,		--| Pointeur à la racine de l'arbre
//		xd_source_list	: Seq Of sourceline,	--| Pointeur à la liste des lignes sources
//		xd_err_count	: num_val,		--| Nombre d'erreurs
//		spare_1 	: void;		--| Libre
//  txtrep	=> ;				--| Representation du texte
//  num_val	=> ;				--| Representation d'entier 16 bits
//
//  BOOLEAN	::= false | true ;

//  false	=> ;
//  true	=> ;
//  nil	=> ;				--| Pointeur vide
//  list	=>				--| Elément lien de liste
//		xd_head 	: void,		--| Tête (pointeur à l'élément)
//		xd_tail 	: void;		--| Suite (pointeur à un élément de liste en général, ou vide)
//  sourceline	=>				--| Ligne de source
//		xd_number	: num_val,		--| Numéro de ligne
//		xd_error_list	: Seq Of error;		--| Pointeur à la liste d'erreurs
//  error	=>
//		xd_srcpos	: Source_Position,		--| Position de l'erreur (ligne colonne)
//		xd_text 	: txtrep;		--| Texte de l'erreur
//  symbol_rep	=>				--| Symbole (identificateur unique répertorié)
//		xd_text 	: txtrep,		--| Pointeur de texte symbole
//		xd_deflist	: Seq Of DEF_NAME;		--| Liste des apparitions du symbole
//  hash	=>				--| Seau de hachage
//		xd_list 	: Seq Of symbol_rep;	--| Liste de symboles du seau
//
//  NON_DIANA	::=	root | txtrep | num_val | BOOLEAN | nil | list		--| Classe des noeuds hors syntaxe propre
//		| sourceline | error | symbol_rep | hash;

//  void	=> ;

--	IDL pour le traitement de grammaire

//  user_root	=>				--| Racine d'arbre syntaxique
//		xd_sourcename	: txtrep,		--| Nom du fichier source
//		xd_grammar	: rule_s,		--| Liste des règles
//		xd_statelist	: state_s,		--| Liste des états
//		xd_structure	: compilation,
//		xd_timestamp	: Integer,
//		spare_3	: void;
//
//  RULE_S	::=	rule_s;
//
//  rule_s	=>				--| Liste de règles
//		xd_list	: Seq Of rule;		--| Pointeur aux éléments de liste
//  rule =>
//		xd_name	: symbol_rep,		--| Nom de la règle
//		xd_list	: Seq Of alt,		--| Liste des alternatives
//		xd_is_nullable	: BOOLEAN,		--| Si génère une châine vide
//		xd_ruleinfo	: ruleinfo;
//  rule =>					--| Règle
//		lx_srcpos	: Source_Position;		--| Position dans le source
//
//  alt	=>
//		xd_list	: Seq Of SYLLABLE,
//		xd_alt_nbr	: Integer,
//		xd_rule	: rule,
//		xd_state_s	: state_s,		--| Liste des états ayant une première alternative donnée
//		xd_semantics	: sem_s;
//  alt	=>
//		lx_srcpos	: Source_Position;
//
//  SYLLABLE	::=	terminal | nonterminal;
//
//  terminal	=>
//		xd_symrep	: symbol_rep,
//		xd_ter_nbr	: Integer;
//  terminal	=>
//		lx_srcpos	: Source_Position;
//  nonterminal	=>
//		xd_symrep	: symbol_rep,
//		xd_rule	: rule;
//  nonterminal	=>
//		lx_srcpos	: Source_Position;
//
//  ruleinfo	=>	xd_list	: Seq Of terminal,		--| initial terminals
//		xd_is_reachable	: BOOLEAN,		-- reachable from start symbol
//		xd_gens_ter_str	: BOOLEAN,		-- generates terminal string
//		xd_timechecked	: Integer,		-- used in initial symbol algorithm;
//		xd_timechanged	: Integer,		-- used in initial symbol algorithm;
//		xd_rule_nbr	: Integer,		-- (temp) only in stat & later
//		xd_init_nonter_s	: rule_s;
//
//  state_s	=>
//		xd_list	: Seq Of state;
//
//  state	=>
//		xd_list	: Seq Of item,
//		xd_state_nbr	: Integer;
//
//  STATE_VOID ::= state | void ;
//  item	=>
//		xd_alternative	: alt,
//		xd_alt_tail	: Seq Of SYLLABLE,
//		xd_syl_nbr	: Integer,		--| which syl; 0 at start of rule
//		xd_goto	: STATE_VOID,
//		xd_follow	: terminal_s;		--| follow terminals
//  terminal_s	=>
//		xd_list	: Seq Of terminal;
//  sem_s	=>
//		xd_list	: Seq Of SEMANTICS,
//		xd_sem_index	: Integer;		--| assigned location
//
//  SEMANTICS	::=	sem_node | sem_op ;
//
//  sem_node	=>
//		xd_sem_op	: Integer,
//		xd_kind	: Integer;
//  sem_op	=>
//		xd_sem_op	: Integer;
//
//  NON_DIANA	::=	user_root | RULE_S | rule | alt
//		| SYLLABLE | ruleinfo | state_s | STATE_VOID
//		| item | terminal_s | sem_s | SEMANTICS;

// end	--| Fin de spécification
