with TEXT_IO;
use  TEXT_IO;
				--------------------
	package body		CODAGE_INTERMEDIAIRE
				--------------------
is

  DEBUG				: BOOLEAN	:= TRUE;

  OPERAND_DISPO			: OPERAND_REF;
  LAST_OPERAND_T			: TEMPORAIRE_T	:= 0;
  LAST_OPERAND_A			: TEMPORAIRE_A	:= 0;

  TABLE_OPERANDS			: array( OPERAND_REF'FIRST+1 .. OPERAND_REF'LAST ) of REC_OPERAND;

  LAST_LBL			: TARGET_LBL_REF;
  LAST_BRANCH			: NUM_BRANCH;
  DERNIERE_REPRISE_CALL		: TARGET_LBL_REF	:= 0;


			--=======--
  function		NEW_OPERAND		return OPERAND_REF
  is
    ALLOUEE	: OPERAND_REF;
  begin

    if OPERAND_DISPO = 0 or else LAST_OPERAND_T = NMAX_TEMPORAIRES_T
    then raise TROP_D_OPERANDS;
    end if;

    ALLOUEE        := OPERAND_DISPO;
    OPERAND_DISPO  := TABLE_OPERANDS( ALLOUEE ).NEXT_FREE;

    LAST_OPERAND_T := LAST_OPERAND_T + 1;
    TABLE_OPERANDS( ALLOUEE ) := (GENRE => DAT_TMP, TMP_T => LAST_OPERAND_T, INACTIF => TRUE);
    TABLE_TEMPORAIRES_T( LAST_OPERAND_T ).LOCALISATIONS := 0;
    return ALLOUEE;

  end	NEW_OPERAND;
	--=======--



			--==--
  procedure		 FREE			( OPERAND :OPERAND_REF )
  is
  begin

    if (OPERAND <= 0) Or (OPERAND > NMAX_OPERANDS) then raise OPERAND_INVALIDE; end if;

    TABLE_OPERANDS( OPERAND ) := ( GENRE => FREE, NEXT_FREE => OPERAND_DISPO, INACTIF => TRUE );
    OPERAND_DISPO := OPERAND;

  end	 FREE;
	--==--



			--===--
  function 		NEW_LBL			return TARGET_LBL_REF is
  begin
    if LAST_LBL = MAX_TARGET_LBLS then raise TROP_DE_REPRISES; end if;

    LAST_LBL := LAST_LBL + 1;
    return LAST_LBL;

  end	NEW_LBL;
	--===--



			--====--
  procedure		STOCK_CP		( FOR_LBL :TARGET_LBL_REF )
  is
  begin
    TARGET_ILOC( FOR_LBL ) := COMPTEUR_PROGRAMME;

    if DEBUG then
      PUT_LINE( INSTR_LOC'IMAGE( COMPTEUR_PROGRAMME ) & " <<" & TARGET_LBL_REF'IMAGE( FOR_LBL ) & ">>" );
    end if;
  end	STOCK_CP;
	--====--



			--==========--
  procedure		MAKE_OPRND_IMM		( OPERAND :OPERAND_REF; IMM_VAL : INTEGER )
  is
  begin
    LAST_OPERAND_T := LAST_OPERAND_T - 1;
    TABLE_OPERANDS( OPERAND ) := ( GENRE => IMM, VALEUR => IMM_VAL, INACTIF => TRUE );

    if DEBUG then
      PUT_LINE( "MAKE_OPRND_IMM     OPERAND=" & OPERAND_REF'IMAGE(OPERAND) & "  IMM_VAL=" & INTEGER'IMAGE( IMM_VAL ) );
    end if;
  end	MAKE_OPRND_IMM;
	--==========--



			--==========--
  procedure		MAKE_OPRND_DAT		( OPERAND :OPERAND_REF;
						  SEG :SEGMENT_NUM; LVL :LEVEL_NUM; OFS :OFFSET_VAL;
						  SIZ :POSITIVE )
  is
  begin
    LAST_OPERAND_T := LAST_OPERAND_T - 1;
    TABLE_OPERANDS( OPERAND ) := ( GENRE => DAT,
			     SEG   => 0, OFS => 0, SIZ => 0, INACTIF => TRUE );

    if DEBUG then
      PUT_LINE( "MAKE_OPRND_DAT     OPERAND=" & OPERAND_REF'IMAGE(OPERAND)
		& "  SEG=" & SEGMENT_NUM'IMAGE( SEG )
		& "  LVL=" & LEVEL_NUM'IMAGE( LVL )
		& "  OFS=" & OFFSET_VAL'IMAGE( OFS )
		& "  SIZ=" & POSITIVE'IMAGE( SIZ )
	    );
    end if;
  end	MAKE_OPRND_DAT;
	--==========--



			--==========--
  procedure		MAKE_OPRND_PRM		( OPERAND :OPERAND_REF; DIRECTION :DIRECTION_DE_PASSAGE )
  is
  begin
    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := ( GENRE		=> PRM,
					PARAMETRE		=> TABLE_OPERANDS( OPERAND ),
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );
    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ).PARAMETRE := ( GENRE => PRM, DIRECTION => DIRECTION,
					PRM_OFS => 0, PRM_SIZ => 0, INACTIF => TRUE );
    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	MAKE_OPRND_PRM;
	--==========--


			--===--
  procedure		ADR1_OP		( RESULTAT :OPERAND_REF; OP: OPCI_ADR1; X1: OPERAND_REF )
  is
  begin
    if TABLE_OPERANDS( RESULTAT ).GENRE = DAT_TMP then

      if LAST_OPERAND_A = NMAX_TEMPORAIRES_A then raise TROP_DE_TEMPORAIRES_A; end if;

      LAST_OPERAND_T := LAST_OPERAND_T - 1;
      LAST_OPERAND_A := LAST_OPERAND_A + 1;
      TABLE_OPERANDS( RESULTAT ) := ( GENRE => ADR_TMP, TMP_A => LAST_OPERAND_A, INACTIF => TRUE );

      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).LOCALISATIONS := 0;
      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).PARAMETRES.GENRE := INDIRECT;
      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).PARAMETRES.DEPLACEMENT := 0;

    end if;

    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := (	GENRE		=> ADR1, ADR1_OP => OP,
					ADR1_X1		=> TABLE_OPERANDS( X1 ),
					ADR1_RESULT	=> TABLE_OPERANDS( RESULTAT ),
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );

    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	ADR1_OP;
	--===--



			--===--
  procedure		ADR2_OP		( RESULTAT :OPERAND_REF; OP: OPCI_ADR2; X1, X2: OPERAND_REF )
  is
  begin
    if TABLE_OPERANDS( RESULTAT ).GENRE = DAT_TMP then

      if LAST_OPERAND_A = NMAX_TEMPORAIRES_A then raise TROP_DE_TEMPORAIRES_A; end if;

      LAST_OPERAND_T := LAST_OPERAND_T - 1;
      LAST_OPERAND_A := LAST_OPERAND_A + 1;
      TABLE_OPERANDS( RESULTAT ) := ( GENRE => ADR_TMP, TMP_A => LAST_OPERAND_A, INACTIF => TRUE );

      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).LOCALISATIONS := 0;
      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).PARAMETRES.GENRE := INDIRECT;
      TABLE_TEMPORAIRES_A( LAST_OPERAND_A ).PARAMETRES.DEPLACEMENT := 0;

    end if;

    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := (	GENRE		=> ADR2, ADR2_OP => OP,
					ADR2_X1		=> TABLE_OPERANDS( X1 ),
					ADR2_X2		=> TABLE_OPERANDS( X2 ),
					ADR2_RESULT	=> TABLE_OPERANDS( RESULTAT ),
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );

    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	ADR2_OP;
	--===--



			--====--
  procedure		FLOT0_OP		( OP :OPCI_FLOT0; ALLOC_DESALLOC :INTEGER := 0 )
  is 
  begin

    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := (	GENRE		=> FLOT0, FLOT0_OP =>OP,
					DESALLOC		=> ALLOC_DESALLOC,
					UNIT => 0, PROC => 0,
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );

    if DEBUG then
      PUT( INSTR_LOC'IMAGE( COMPTEUR_PROGRAMME ) & ASCII.HT & OPCI_FLOT0'IMAGE( OP ) );
      if OP /= UNLINK then PUT( ' ' & INTEGER'IMAGE( ALLOC_DESALLOC ) ); end if;
      NEW_LINE;
    end if;

    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	FLOT0_OP;
	--====--


			--====--
  procedure		FLOT1_OP	( OP :OPCI_FLOT1; TARGET :TARGET_LBL_REF )
  is
  begin

    if LAST_BRANCH = MAX_BRANCHS then raise TROP_IFLOTS1; end if;

    LAST_BRANCH := LAST_BRANCH + 1;
    BRANCH_ILOC( LAST_BRANCH ) := COMPTEUR_PROGRAMME;

    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := (	GENRE		=> FLOT1, FLOT1_OP =>OP,
					FLOT1_SAUT	=> TARGET,
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );

    if DEBUG then
      PUT_LINE( INSTR_LOC'IMAGE( COMPTEUR_PROGRAMME ) & ASCII.HT & OPCI_FLOT1'IMAGE( OP )
	      & " <<" & TARGET_LBL_REF'IMAGE( TARGET ) & ">>" );
    end if;

    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	FLOT1_OP;
	--====--



			--====--
  procedure		FRAME_OP		( OP :OPCI_FRAME; ALLOC :INTEGER := 0 )
  is 
  begin

    TABLE_INSTRUCTIONS( COMPTEUR_PROGRAMME ) := (	GENRE		=> FRAME, FRAME_OP =>OP,
					ALLOC		=> ALLOC,
					FIN_BLOC		=> FALSE,
					BLOC_ENTREE_LATERALE => 0, BLOC_SORTIE_LATERALE => 0 );

    if DEBUG then
      PUT( INSTR_LOC'IMAGE( COMPTEUR_PROGRAMME ) & ASCII.HT & OPCI_FRAME'IMAGE( OP ) );
      if OP /= UNLINK then PUT( ' ' & INTEGER'IMAGE( ALLOC ) ); end if;
      NEW_LINE;
    end if;

    COMPTEUR_PROGRAMME := COMPTEUR_PROGRAMME + 1;

  end	FRAME_OP;
	--====--




begin
  for INDICE in TABLE_OPERANDS'RANGE loop
    TABLE_OPERANDS( INDICE ) := ( GENRE => FREE, NEXT_FREE => INDICE - 1, INACTIF => TRUE );
  end loop;
  OPERAND_DISPO := NMAX_OPERANDS;

end	CODAGE_INTERMEDIAIRE;
	--------------------