WITH TEXT_IO, IDL;
USE  TEXT_IO, IDL;
--|-------------------------------------------------------------------------------------------------
--|	EMITS
--|-------------------------------------------------------------------------------------------------
PACKAGE EMITS IS

  MAX_LABEL		: CONSTANT	:= 30_000;				--| NB MAX D'ETIQUETTES DE SAUT
  MAX_OFFSET		: CONSTANT	:= 10_000;				--|
  MAX_LEVEL		: CONSTANT	:= 200;					--| NB MAX DE NIVEAUX D'IMBRICATION
   
  TYPE LABEL_TYPE		IS NEW NATURAL RANGE 0..MAX_LABEL;				--| TYPE ETIQUETTE
  SUBTYPE OFFSET_TYPE	IS INTEGER RANGE -MAX_OFFSET..MAX_OFFSET;			--| TYPE DECALAGE
  SUBTYPE LEVEL_TYPE	IS NATURAL RANGE 0..MAX_LEVEL;				--| TYPE NIVEAU D'IMBRICATION
   
  ADDR_SIZE		: CONSTANT	:= 4;					--| ADRESSES SUR 32 BITS
  ADDR_AL			: CONSTANT	:= 2;
  BOOL_SIZE		: CONSTANT	:= 1;					--| BOOLEEN SUR 1 OCTET
  BOOL_AL			: CONSTANT	:= 1;
  CHAR_SIZE		: CONSTANT	:= 1;					--| CARACTERE SUR 8 BITS
  CHAR_AL			: CONSTANT	:= 1;
  INTG_SIZE		: CONSTANT	:= 4;					--| ENTIER SUR 32 BITS
  INTG_AL			: CONSTANT	:= 2;
  STACK_AL		: CONSTANT	:= 2;
  ARRAY_AL		: CONSTANT	:= 2;
  RECORD_AL		: CONSTANT	:= 2;
   
  FIRST_PARAM_OFFSET	: CONSTANT OFFSET_TYPE	:= 10;
  FIRST_LOCAL_VAR_OFFSET	: CONSTANT OFFSET_TYPE	:= 0;
  RELATIVE_RESULT_OFFSET	: CONSTANT OFFSET_TYPE	:= 2;
      
  TYPE OP_CODE		IS (			--| CODES OPERATION DU ACODE POLONAIS
	ABO,   ABSV,  ACA,   ACC,   ACT,   ADD,   ALO,   BAND,  CHR,
	TRAP,  CSTA,  CSTI,  CSTS,  CALL,  DEC,   DIV,   DPL,   EAC,
	EEX,   ENT,   EQ,    ETD,   ETE,   ETK,   ETR,   EXC,   EXH,
	EXL,   EXP,   JMPF,  FRE,   GE,    GET,   GT,    INC,   IND,
	IXA,   LAO,   LCA,   LDA,   LDC,   LDO,   LE,    LT,    LOD,
	LVB,   MODU,  MOV,   MST,   MUL,   MVV,   NEG,   NEQ,   BNOT,
	BOR,   PKB,   PKG,   PRO,   PUT,   QUIT,  RAI,   REMN,  RET,
	RFL,   RFP,   SRO,   STO,   STR,   SUB,   SWP,   JMPT,  JMP,
	BXOR,  XJP
	);
      
  PACKAGE OP_CODE_IO	IS NEW ENUMERATION_IO ( OP_CODE );				--| POUR ECRIRE LES CODES SUR LE FICHIER DE SORTIE
   
  TYPE CODE_TYPE		IS ( A, B, C, I );						--| ADDRESS BOOLEAN CHARACTER INTEGER
      
  PACKAGE CODE_TYPE_IO	IS NEW ENUMERATION_IO ( CODE_TYPE );
   
  TYPE STD_PROC	IS (
	AR1, AR2, CLB, CLN, CNT, CVB, CYA, LBD, LEN, PUA, TRM
      	);
   
  COMMENTS_ON		: BOOLEAN	:= TRUE;						--| COMMUTATEUR POUR L'EMISSION DES COMMENTAIRES AVEC LE CODE
   
  SUBTYPE COMP_UNIT_NBR	IS NATURAL RANGE 0..255;					--| SOUS TYPE NO D'UNITE DE COMPILATION
   
  CUR_COMP_UNIT		: COMP_UNIT_NBR;						--| NO D'UNITE DE COMPILATION COURANTE
  GENERATE_CODE		: BOOLEAN	:= TRUE;						--| COMMUTATEUR POUR LA GENERATION DU CODE
  LEVEL			: LEVEL_TYPE;						--| NIVEAU D'IMBRICATION COURANT
   
  OFFSET_ACT		: OFFSET_TYPE;
  OFFSET_MAX		: OFFSET_TYPE;
  TOP_ACT			: OFFSET_TYPE;						--| TOP OF STACK ACTUEL (LA PILE CROIT POSITIVEMENT)
  TOP_MAX			: OFFSET_TYPE;						--| TOP OF STACK MAXIMAL
      
  PARAM_SIZE		: NATURAL;						--| TAILLE DES PARAMETRES DE PROCEDURE EN OCTETS
  RESULT_SIZE		: NATURAL;						--| TAILLE DU RESULTAT DE FONCTION EN OCTETS
  FUN_RESULT_OFFSET		: OFFSET_TYPE	:= 0;
  FUNCTION_RESULT		: TREE;
   
   
  SKIP_LBL, HANDLER_BEGIN_LBL	: LABEL_TYPE;						--| UTILISES POUR LES EXCEPTIONS HANDLERS
  ENCLOSING_BODY		: TREE;
  CHOICE_OTHERS_FLAG	: BOOLEAN	:= FALSE;
      
  AFTER_IF_LBL		: LABEL_TYPE;
   
  BEFORE_LOOP_LBL		: LABEL_TYPE;
  AFTER_LOOP_LBL		: LABEL_TYPE;
  LOOP_STM_S		: TREE;
  LOOP_OP_INC_DEC		: OP_CODE;						--| POUR LE TRAITEMENT DES BOUCLES FOR REVERSE
  LOOP_OP_GT_LT		: OP_CODE;						--| DE MEME
  
  TYPE_SYMREP		: TREE;			--| UTILISE POUR LES OBJECT_DECL VAR CONST
      
  PROCEDURE OPEN_OUTPUT_FILE	( FILE_NAME :STRING );
  PROCEDURE CLOSE_OUTPUT_FILE;
  PROCEDURE WRITE_LABEL	( LBL :LABEL_TYPE; COMMENT :STRING := "" );
  PROCEDURE GEN_LBL_ASSIGNMENT	( LBL :LABEL_TYPE; N :NATURAL );
  PROCEDURE EMIT_COMMENT	( COMMENT :STRING );		--| ESSENTIELLEMENT POUR INDIQUER LES PARTIES RESTANT A FAIRE
  PROCEDURE EMIT		( OC :OP_CODE; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; CT :CODE_TYPE; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; B :BOOLEAN; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; C :CHARACTER; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; LBL :LABEL_TYPE; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; I :INTEGER; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; CT :CODE_TYPE; I :INTEGER; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; S :STRING; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; NUM, LBL :LABEL_TYPE; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; LBL :LABEL_TYPE; S :STRING; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; I :INTEGER; LBL :LABEL_TYPE; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; IA, IB :INTEGER; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; CT :CODE_TYPE; IA, IB :INTEGER; COMMENT :STRING := "" );
  PROCEDURE EMIT		( OC :OP_CODE; I :INTEGER; S :STRING; COMMENT :STRING := "" );
  PROCEDURE EMIT		( P :STD_PROC; COMMENT :STRING := "" );
  PROCEDURE GEN_LOAD_ADDR	( COMP_UNIT_NUMBER :COMP_UNIT_NBR; LVL :LEVEL_TYPE; OFFSET :INTEGER; COMMENT :STRING := "" );
  PROCEDURE GEN_LOAD	( CT :CODE_TYPE; COMP_UNIT_NUMBER :COMP_UNIT_NBR; LVL :LEVEL_TYPE; OFFSET :INTEGER; COMMENT :STRING := "" );
  PROCEDURE GEN_STORE	( CT :CODE_TYPE; COMP_UNIT_NUMBER :COMP_UNIT_NBR; LVL :LEVEL_TYPE; OFFSET :INTEGER; COMMENT :STRING := "" );
   
  FUNCTION  NEXT_LABEL			RETURN LABEL_TYPE;
  PROCEDURE INC_LEVEL;
  PROCEDURE DEC_LEVEL;
  PROCEDURE INC_OFFSET	( I :INTEGER );
  PROCEDURE ALIGN		( AL :INTEGER );
       
       
  PROCEDURE PERFORM_RETURN	( ENCLOSING_BLOCK_BODY :TREE );
  FUNCTION  TYPE_SIZE	( TYPE_SPEC :TREE )		RETURN NATURAL;
  FUNCTION  CODE_TYPE_OF	( EXP_OR_TYPE_SPEC :TREE )	RETURN CODE_TYPE;
   
  FUNCTION  NUMBER_OF_DIMENSIONS	( EXP :TREE )		RETURN NATURAL;
  PROCEDURE GET_CLO		( OBJECT :TREE; COMP_UNIT :OUT COMP_UNIT_NBR;	--| DONNE L UNITE LE NIVEAU ET L OFFSET D UN OBJET
		  LVL :OUT LEVEL_TYPE; OFS :OUT OFFSET_TYPE );
  FUNCTION  CONSTRAINED	( TYPE_SPEC :TREE ) RETURN BOOLEAN;
  PROCEDURE LOAD_TYPE_SIZE	( TYPE_SPEC :TREE );


  ILLEGAL_OP_CODE, STATIC_LEVEL_OVERFLOW, STATIC_LEVEL_UNDERFLOW,
  STATIC_OFFSET_OVERFLOW	: EXCEPTION;
       
--|-------------------------------------------------------------------------------------------------
END EMITS;